DELETE http://localhost:8080/jobs/2e9abbad-c109-47cc-a60e-3ad31f47b78b
content-type: application/json

{
  "title": "DevOps Engineer",
  "description": "HarfangLab is a cybersecurity scale-up, and we have developed an Endpoint Detection and Response (EDR) software to detect and mitigate modern cyberattacks on a company's workstations and servers. Our algorithms detect abnormal behaviors and generate security alerts or block program execution.",
  "location": "France",
  "salary": "60k",
  "duties": [
    "Build and Improve the Product: Add new features and enhancements to make it even better.",
    "Optimize CI/CD Pipelines: Collaborate with developers to ensure the pipeline is as efficient as possible, using GitLab-CI, Kubernetes (K8s), Helm, KubeVirt, and a suite of complementary tools.",
    "Automate Client On-Premise Installations: Help with initial deployments and develop automation to make subsequent setups seamless. We use Ansible, k3s, Helm, and some custom Python code.",
    "Monitor and Maintain Internal Cloud and Infrastructure: Ensure smooth operation, fix issues, and automate repairs across our internal cloud stacks.",
    "R&D for New Tools and Frameworks: Stay ahead of the curve by researching and experimenting with new technologies that could benefit our team."
  ],
  "url": "https://harfanglab-1666711819.teamtailor.com/jobs/5349829-devops-engineer"
}