PUT http://localhost:8080/jobs/b9178b32-1f0e-4e48-9417-fcc548b56f29
content-type: application/json

{
  "title": "Senior Golang Engineer",
  "description": "For Sky: Children of the Light, that game company has developed several backend services capable of handling a massive amount of concurrent users. Providing a reliable and low latency experience for our players is a priority. We build, test, and maintain systems for account and login, user-generated content, and various persistent gameplay systems.",
  "location": "United States",
  "salary": "95k",
  "duties": [
    "Have 5+ years experience working on the backend for an MMO or high-volume, low-latency web services.",
    "Have deep experience with both relational and non-relational databases (PostgreSQL, MongoDB, Redis).",
    "Be comfortable deploying containerized services to a kubernetes cluster.",
    "Be familiar with both microservice and monolith architectures.",
    "Be familiar with creating unit tests, stress tests, and integration tests.",
    "Have experience with multiple cloud providers like AWS or GCP.",
    "Have experience with Kubernetes, Helm, and Docker"
  ],
  "url": "https://jobs.ashbyhq.com/thatgamecompany/de259908-5ad8-4004-a1da-3872842274d5"
}